Add monitoring pages
coding-blocks/poker pull request #17
Opened 2020-05-25 05:32 UTC by prateek2211

fix #16 
* [X] Create View's folder structure
* [X] Implement Page Views
   * [X] Application list page view with pagination - /applications
   * [X] Application list page template
   * [X] Application detail view which lists all the jobs paginated - /applications/<id>
   * [X] Application detail view template
   * [X] Jobs detail view which lists all the logs paginated - /jobs/<id>
   * [X] Jobs detail view template
        * [X] Should have an execute now button
        * [ ] Can apply filter on Logs ( status, created_at )
* [X] Test the application locally and attach screenshots while making the final submission.

2020-05-25 05:33 UTC, prateek2211 commented
Screenshots:
![Screenshot from 2020-05-25 10-58-05](https://user-images.githubusercontent.com/42961174/82781412-5b671300-9e77-11ea-8a21-f0d98bc15196.png)
![Screenshot from 2020-05-25 10-59-03](https://user-images.githubusercontent.com/42961174/82781415-5d30d680-9e77-11ea-8f46-099da3a286cd.png)
![Screenshot from 2020-05-25 10-59-16](https://user-images.githubusercontent.com/42961174/82781416-5e620380-9e77-11ea-970b-6e3431524e74.png)

2020-05-25 05:35 UTC, prateek2211 commented
# TODO:
* Add filter on log page
* Action on delete button
* Action on execute button

2020-05-25 05:46 UTC, prateek2211 commented
@jatinkatyal13 Please check if the UI and code architecture going the right way.

2020-05-25 10:30 UTC, jatinkatyal13 requested changes

2020-05-25 10:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +    context = super(JobDetailView, self).get_context_data(object_list=object_list,
Nitpick, but in python3 you can simply write `super().get_context_data`

2020-05-25 10:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +    object_list = log_queryset.order_by('pk')
`order_by('-created_at')`

2020-05-25 10:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +    object_list = self.get_object().job_set.order_by('pk')
`order_by('-created_at')`

2020-05-25 10:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +    context = super(ApplicationDetailView, self).get_context_data(object_list=object_list, **kwargs)
use `super()`

2020-05-25 10:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +class ApplicationDetailView(generic.DetailView, MultipleObjectMixin):
It won't make a difference here but Mixins should always be placed before the views

2020-05-25 10:32 UTC, jatinkatyal13 commented
As far as UI is concerned it's good. We'll be needing more feedback to know what all information can be displayed to the user, until then this looks good for the MVP.

2020-05-25 10:53 UTC, prateek2211 commented on cron/views/pages/views.py
> +    object_list = self.get_object().job_set.order_by('pk')
Job doesn't contain field `created_at`

2020-05-25 10:59 UTC, prateek2211 commented
@jatinkatyal13 For delete and execute, do we need some POST pages endpoints or
some API endpoint and use AJAX

2020-05-25 11:29 UTC, jatinkatyal13 commented
So let's drop the delete button as it'll be handled in the admin panel and right now the UI is only for the monitoring

For execute now let's have POST API endpoint and we'll call the URL using the JQuery from the frontend.

2020-05-25 11:30 UTC, jatinkatyal13 commented on cron/views/pages/views.py
> +    object_list = self.get_object().job_set.order_by('pk')
oh my bad! Let's order job on pk only

2020-05-25 12:55 UTC, prateek2211 commented
@jatinkatyal13 Do I need to create execute jobs API in this PR, or will there be a separate issue for that

2020-05-25 13:40 UTC, jatinkatyal13 commented
E2E flow for executing job and monitoring is the what we aim in this PR and hence, you'll need to create the API as well.

For filter design, we can simply have different input fields on the top of the table that'll help filter different columns

2020-05-26 14:35 UTC, jatinkatyal13 commented
I've reviewed the execute API part and it's a job well done.

2020-05-26 14:59 UTC, prateek2211 commented
@jatinkatyal13 So, I guess just filter part is remaining in this PR?

2020-05-30 06:39 UTC, prateek2211 commented
@jatinkatyal13 I have added filter in logs page.

Sorry for the delay, because I was sick

2020-05-30 10:05 UTC, jatinkatyal13 approved these changes

2020-05-30 10:05 UTC, merged