FIX-8: Install nginx, added nginx.conf file serves static files and proxy pass then updated entrypoint script and collecting static files before running entrypoint script.
coding-blocks/poker pull request #9
Opened 2020-05-16 22:14 UTC by A4ANK

Signed-off-by: ANKUR DHAKAR <dhakar.ankur18@gmail.com>

Fixes #8 

Changes:   Install nginx, added nginx.conf file serves static files and proxy pass then updated entrypoint script and collecting static files before running entrypoint script.

2020-05-17 11:18 UTC, jatinkatyal13 requested changes

2020-05-17 11:18 UTC, jatinkatyal13 commented on poker/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0','192.168.56.27']
Please add * as of now rather than hardcoding IPs

2020-05-17 11:18 UTC, jatinkatyal13 commented on nginx.conf
> +
add the `/static` location here itself and use alias directive rather than root

2020-05-17 11:18 UTC, jatinkatyal13 commented on nginx.conf
> +upstream poker  {
remove unused upstream declaration

2020-05-17 11:18 UTC, jatinkatyal13 commented on docker-compose.yml
> +    image: 'postgres:10'
Let's stick with current compose file

2020-05-17 11:18 UTC, jatinkatyal13 commented on Dockerfile
> +RUN mkdir -p /run/nginx
Why do we need this folder?

2020-05-17 16:20 UTC, jatinkatyal13 requested changes

2020-05-17 16:20 UTC, jatinkatyal13 commented on start.sh
> +yes yes| python manage.py collectstatic
remove `yes yes`

2020-05-17 16:20 UTC, jatinkatyal13 commented on docker-compose.yml
> +#    env_file:
remove comments it is a required config

2020-05-17 16:20 UTC, jatinkatyal13 commented on Dockerfile
> +RUN mkdir -p /run/nginx
we don't need to create this directory

2020-05-21 06:17 UTC, A4ANK commented
Please review this pull request.

2020-05-21 15:11 UTC, closed without merging